apiVersion: v2
name: sausage-store
description: Umbrella chart for Sausage Store (backend, frontend, report, infra)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: "0.1.0"
    repository: "file://charts/backend"
    condition: backend.enabled
  - name: backend-report
    version: "0.1.0"
    repository: "file://charts/backend-report"
    condition: backendReport.enabled
  - name: frontend
    version: "0.1.0"
    repository: "file://charts/frontend"
    condition: frontend.enabled
  - name: infra
    version: "0.1.0"
    repository: "file://charts/infra"
    condition: infra.enabled