backend:
  resources:
    requests:
      memory: "128Mi"   # было 256Mi
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

frontend:
  resources:
    requests:
      memory: "32Mi"    # было 64Mi
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

backend-report:
  resources:
    requests:
      memory: "64Mi"    # было 128Mi
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

infra:
  postgresql:
    resources:
      requests:
        memory: "128Mi" # было 256Mi
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  mongodb:
    resources:
      requests:
        memory: "128Mi" # было 256Mi
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "300m"