apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-init
data:
  init.js: |
    db = db.getSiblingDB("admin");
    if (!db.getUser("{{ .Values.mongodb.reports.user }}")) {
      db.createUser({
        user: "{{ .Values.mongodb.reports.user }}",
        pwd: "{{ .Values.mongodb.reports.password }}",
        roles: [
          { role: "readWrite", db: "{{ .Values.mongodb.reports.database }}" }
        ]
      });
    }